version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
artifacts:
  base-directory: ./build
  files: 
    - "**/*"
